# https://github.com/marketplace/actions/profile-readme-development-stats
name: Waka Readme

on:
  schedule:
      # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "WakaTime Overview"
          SHOW_TIMEZONE: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_OS: "False"
          SHOW_LOC_CHART: "False"
          IGNORED_REPOS: ".github,ipoetdev"